import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black">
        <nav className="flex items-center gap-6 px-6 py-4 border-b-2 border-white/15 bg-black">
          <Link
            href="/"
            className="text-sm font-bold uppercase tracking-wide text-white/60 hover:text-lime-400 transition-colors"
          >
            Анализ вакансий
          </Link>
          <Link
            href="/cover-letter"
            className="text-sm font-bold uppercase tracking-wide text-white/60 hover:text-lime-400 transition-colors"
          >
            Сопроводительное письмо
          </Link>
          <Link
            href="/interview-prep"
            className="text-sm font-bold uppercase tracking-wide text-white/60 hover:text-lime-400 transition-colors"
          >
            Подготовка к собеседованию
          </Link>
        </nav>
        {children}</body>
    </html>
  );
}
